# Generated by Django 4.1.7 on 2023-03-27 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the base.', max_length=200)),
                ('location', models.CharField(help_text='Enter the state for this base.', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Battalion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the Battalion.', max_length=200)),
                ('base', models.ManyToManyField(help_text='Select a base for this Battalion.', to='app.base')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an Army Command (e.g. TRADOC)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the Company.', max_length=200)),
                ('base', models.ManyToManyField(help_text='Select a base for this Battalion.', to='app.base')),
                ('battalion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.battalion')),
            ],
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the Brigade.', max_length=200)),
                ('base', models.ManyToManyField(help_text='Select a base for this Brigade.', null=True, to='app.base')),
                ('command', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.command')),
            ],
        ),
        migrations.AddField(
            model_name='battalion',
            name='brigade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.brigade'),
        ),
    ]
