# Generated by Django 4.1.7 on 2023-03-27 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_base_battalion_command_company_brigade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.base'),
        ),
    ]
