# Generated by Django 4.1.7 on 2023-03-27 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_base'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
