# Generated by Django 4.1.7 on 2023-04-01 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
