# Generated by Django 4.1.7 on 2023-04-01 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='upload',
            field=models.FileField(default='test', upload_to='uploads/base/<django.db.models.fields.CharField>/'),
            preserve_default=False,
        ),
    ]
