# Generated by Django 4.1.7 on 2023-04-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_base_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/base/<django.db.models.fields.CharField>/'),
        ),
    ]
