# Generated by Django 4.1.7 on 2023-04-01 20:30

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_base_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=app.models.generate_filename)),
            ],
        ),
        migrations.AddField(
            model_name='base',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.modelfiles'),
        ),
    ]
