# Generated by Django 4.1.7 on 2023-04-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_modelfiles_base_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='file',
        ),
        migrations.AddField(
            model_name='modelfiles',
            name='base',
            field=models.ManyToManyField(related_name='files', to='app.base'),
        ),
        migrations.AddField(
            model_name='modelfiles',
            name='name',
            field=models.CharField(default='null', help_text='Enter file name.', max_length=200),
            preserve_default=False,
        ),
    ]
