# Generated by Django 4.1.7 on 2023-04-01 21:14

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_base_file_modelfiles_base_modelfiles_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the file name', max_length=200)),
                ('file', models.FileField(upload_to=app.models.generate_filename)),
                ('base', models.ManyToManyField(related_name='files', to='app.base')),
            ],
        ),
        migrations.DeleteModel(
            name='ModelFiles',
        ),
    ]
