# Generated by Django 4.1.7 on 2023-04-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_file_delete_modelfiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='base',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.AddField(
            model_name='base',
            name='files',
            field=models.ManyToManyField(to='app.file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m%d'),
        ),
    ]
