# Generated by Django 4.1.7 on 2023-04-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_file_base_remove_file_name_base_files_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='file', help_text='Enter the file name.', max_length=200),
            preserve_default=False,
        ),
    ]
