# Generated by Django 4.1.7 on 2023-04-01 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='files',
        ),
        migrations.AddField(
            model_name='file',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.base'),
        ),
    ]
