# Generated by Django 4.1.7 on 2023-04-01 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_base_files_file_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='battalion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.battalion'),
        ),
        migrations.AddField(
            model_name='file',
            name='brigade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.brigade'),
        ),
        migrations.AddField(
            model_name='file',
            name='command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.command'),
        ),
        migrations.AddField(
            model_name='file',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
    ]
