# Generated by Django 4.1.7 on 2023-04-01 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_customuser'),
        ('accounts', '0004_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='base',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.base'),
        ),
    ]
