# Generated by Django 4.2 on 2023-04-12 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_file_battalion_file_brigade_file_command_and_more'),
        ('accounts', '0006_customuser_brigade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='battalion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app.battalion'),
        ),
    ]
